imputeDataDir: "/path/to/impute_tools" # folder contains ALL_1000G_phase1integrated_v3_impute
sample_ref: "/path/to/impute_tools/ALL_1000G_phase1integrated_v3_impute/ALL_1000G_phase1integrated_v3.sample"
imputeTraits: "/path/to/imputeTraits" # source folder of imputeTraits, where all trait modules can be found
plink: "/path/to/impute_tools/plink/plink"
shapeit: "/path/to/impute_tools/shapeit/shapeit"
impute2: "/path/to/impute_tools/impute_v2.3.2_x86_64_static/impute2"
gtool: "/path/to/impute_tools/gtool"
